// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: reactionTypes.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReactionTypes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reacts string `protobuf:"bytes,2,opt,name=reacts,proto3" json:"reacts,omitempty"`
}

func (x *ReactionTypes) Reset() {
	*x = ReactionTypes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReactionTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionTypes) ProtoMessage() {}

func (x *ReactionTypes) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionTypes.ProtoReflect.Descriptor instead.
func (*ReactionTypes) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{0}
}

func (x *ReactionTypes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReactionTypes) GetReacts() string {
	if x != nil {
		return x.Reacts
	}
	return ""
}

type PostReactionTypesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reacts string `protobuf:"bytes,1,opt,name=reacts,proto3" json:"reacts,omitempty"`
}

func (x *PostReactionTypesRequest) Reset() {
	*x = PostReactionTypesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostReactionTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReactionTypesRequest) ProtoMessage() {}

func (x *PostReactionTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReactionTypesRequest.ProtoReflect.Descriptor instead.
func (*PostReactionTypesRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{1}
}

func (x *PostReactionTypesRequest) GetReacts() string {
	if x != nil {
		return x.Reacts
	}
	return ""
}

type PostReactionTypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactionTypes *ReactionTypes `protobuf:"bytes,1,opt,name=reactionTypes,proto3" json:"reactionTypes,omitempty"`
}

func (x *PostReactionTypesResponse) Reset() {
	*x = PostReactionTypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostReactionTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReactionTypesResponse) ProtoMessage() {}

func (x *PostReactionTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReactionTypesResponse.ProtoReflect.Descriptor instead.
func (*PostReactionTypesResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{2}
}

func (x *PostReactionTypesResponse) GetReactionTypes() *ReactionTypes {
	if x != nil {
		return x.ReactionTypes
	}
	return nil
}

type GetReactionTypeIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetReactionTypeIDRequest) Reset() {
	*x = GetReactionTypeIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactionTypeIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionTypeIDRequest) ProtoMessage() {}

func (x *GetReactionTypeIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionTypeIDRequest.ProtoReflect.Descriptor instead.
func (*GetReactionTypeIDRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{3}
}

func (x *GetReactionTypeIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReactionTypeIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactionTypes *ReactionTypes `protobuf:"bytes,1,opt,name=reactionTypes,proto3" json:"reactionTypes,omitempty"`
}

func (x *GetReactionTypeIDResponse) Reset() {
	*x = GetReactionTypeIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactionTypeIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionTypeIDResponse) ProtoMessage() {}

func (x *GetReactionTypeIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionTypeIDResponse.ProtoReflect.Descriptor instead.
func (*GetReactionTypeIDResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{4}
}

func (x *GetReactionTypeIDResponse) GetReactionTypes() *ReactionTypes {
	if x != nil {
		return x.ReactionTypes
	}
	return nil
}

type GetReactionTypesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReactionTypesRequest) Reset() {
	*x = GetReactionTypesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactionTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionTypesRequest) ProtoMessage() {}

func (x *GetReactionTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionTypesRequest.ProtoReflect.Descriptor instead.
func (*GetReactionTypesRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{5}
}

type GetReactionTypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactionTypes []*ReactionTypes `protobuf:"bytes,1,rep,name=reactionTypes,proto3" json:"reactionTypes,omitempty"`
}

func (x *GetReactionTypesResponse) Reset() {
	*x = GetReactionTypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactionTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionTypesResponse) ProtoMessage() {}

func (x *GetReactionTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionTypesResponse.ProtoReflect.Descriptor instead.
func (*GetReactionTypesResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{6}
}

func (x *GetReactionTypesResponse) GetReactionTypes() []*ReactionTypes {
	if x != nil {
		return x.ReactionTypes
	}
	return nil
}

type Reactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReactType string `protobuf:"bytes,2,opt,name=reactType,proto3" json:"reactType,omitempty"`
	PostId    string `protobuf:"bytes,3,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId    string `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *Reactions) Reset() {
	*x = Reactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reactions) ProtoMessage() {}

func (x *Reactions) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reactions.ProtoReflect.Descriptor instead.
func (*Reactions) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{7}
}

func (x *Reactions) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reactions) GetReactType() string {
	if x != nil {
		return x.ReactType
	}
	return ""
}

func (x *Reactions) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Reactions) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PostReactionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactType string `protobuf:"bytes,1,opt,name=reactType,proto3" json:"reactType,omitempty"`
	PostId    string `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *PostReactionsRequest) Reset() {
	*x = PostReactionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostReactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReactionsRequest) ProtoMessage() {}

func (x *PostReactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReactionsRequest.ProtoReflect.Descriptor instead.
func (*PostReactionsRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{8}
}

func (x *PostReactionsRequest) GetReactType() string {
	if x != nil {
		return x.ReactType
	}
	return ""
}

func (x *PostReactionsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostReactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PostReactionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reactions *Reactions `protobuf:"bytes,1,opt,name=reactions,proto3" json:"reactions,omitempty"`
}

func (x *PostReactionsResponse) Reset() {
	*x = PostReactionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostReactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReactionsResponse) ProtoMessage() {}

func (x *PostReactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReactionsResponse.ProtoReflect.Descriptor instead.
func (*PostReactionsResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{9}
}

func (x *PostReactionsResponse) GetReactions() *Reactions {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type GetUserByPostIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId    string `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	ReactType string `protobuf:"bytes,2,opt,name=reactType,proto3" json:"reactType,omitempty"`
}

func (x *GetUserByPostIDRequest) Reset() {
	*x = GetUserByPostIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByPostIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByPostIDRequest) ProtoMessage() {}

func (x *GetUserByPostIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByPostIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByPostIDRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserByPostIDRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetUserByPostIDRequest) GetReactType() string {
	if x != nil {
		return x.ReactType
	}
	return ""
}

type GetUserByPostIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reactions []*Reactions `protobuf:"bytes,1,rep,name=reactions,proto3" json:"reactions,omitempty"`
}

func (x *GetUserByPostIDResponse) Reset() {
	*x = GetUserByPostIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByPostIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByPostIDResponse) ProtoMessage() {}

func (x *GetUserByPostIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByPostIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByPostIDResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserByPostIDResponse) GetReactions() []*Reactions {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type GetReactByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetReactByUserIDRequest) Reset() {
	*x = GetReactByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactByUserIDRequest) ProtoMessage() {}

func (x *GetReactByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetReactByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{12}
}

func (x *GetReactByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetReactByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reactions []*Reactions `protobuf:"bytes,1,rep,name=reactions,proto3" json:"reactions,omitempty"`
}

func (x *GetReactByUserIDResponse) Reset() {
	*x = GetReactByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReactByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactByUserIDResponse) ProtoMessage() {}

func (x *GetReactByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetReactByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{13}
}

func (x *GetReactByUserIDResponse) GetReactions() []*Reactions {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type DeleteReactionByPostIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId string `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
}

func (x *DeleteReactionByPostIDRequest) Reset() {
	*x = DeleteReactionByPostIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionByPostIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionByPostIDRequest) ProtoMessage() {}

func (x *DeleteReactionByPostIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionByPostIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteReactionByPostIDRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteReactionByPostIDRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type DeleteReactionByPostIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *DeleteReactionByPostIDResponse) Reset() {
	*x = DeleteReactionByPostIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionByPostIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionByPostIDResponse) ProtoMessage() {}

func (x *DeleteReactionByPostIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionByPostIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteReactionByPostIDResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteReactionByPostIDResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

type DeleteReactionByUserPostIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId string `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *DeleteReactionByUserPostIDRequest) Reset() {
	*x = DeleteReactionByUserPostIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionByUserPostIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionByUserPostIDRequest) ProtoMessage() {}

func (x *DeleteReactionByUserPostIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionByUserPostIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteReactionByUserPostIDRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteReactionByUserPostIDRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *DeleteReactionByUserPostIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteReactionByUserPostIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *DeleteReactionByUserPostIDResponse) Reset() {
	*x = DeleteReactionByUserPostIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReactionByUserPostIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionByUserPostIDResponse) ProtoMessage() {}

func (x *DeleteReactionByUserPostIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionByUserPostIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteReactionByUserPostIDResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteReactionByUserPostIDResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

type UpdateReactionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReactType string `protobuf:"bytes,1,opt,name=reactType,proto3" json:"reactType,omitempty"`
	PostId    string `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UpdateReactionsRequest) Reset() {
	*x = UpdateReactionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReactionsRequest) ProtoMessage() {}

func (x *UpdateReactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReactionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateReactionsRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateReactionsRequest) GetReactType() string {
	if x != nil {
		return x.ReactType
	}
	return ""
}

func (x *UpdateReactionsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdateReactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateReactionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reactions *Reactions `protobuf:"bytes,1,opt,name=reactions,proto3" json:"reactions,omitempty"`
}

func (x *UpdateReactionsResponse) Reset() {
	*x = UpdateReactionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReactionsResponse) ProtoMessage() {}

func (x *UpdateReactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReactionsResponse.ProtoReflect.Descriptor instead.
func (*UpdateReactionsResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateReactionsResponse) GetReactions() *Reactions {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type TotalReactionCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId string `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
}

func (x *TotalReactionCountRequest) Reset() {
	*x = TotalReactionCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalReactionCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalReactionCountRequest) ProtoMessage() {}

func (x *TotalReactionCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalReactionCountRequest.ProtoReflect.Descriptor instead.
func (*TotalReactionCountRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{20}
}

func (x *TotalReactionCountRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type TotalReactionCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count string `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TotalReactionCountResponse) Reset() {
	*x = TotalReactionCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalReactionCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalReactionCountResponse) ProtoMessage() {}

func (x *TotalReactionCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalReactionCountResponse.ProtoReflect.Descriptor instead.
func (*TotalReactionCountResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{21}
}

func (x *TotalReactionCountResponse) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

type ReactionCountByTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId    string `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	ReactType string `protobuf:"bytes,2,opt,name=reactType,proto3" json:"reactType,omitempty"`
}

func (x *ReactionCountByTypeRequest) Reset() {
	*x = ReactionCountByTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReactionCountByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionCountByTypeRequest) ProtoMessage() {}

func (x *ReactionCountByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionCountByTypeRequest.ProtoReflect.Descriptor instead.
func (*ReactionCountByTypeRequest) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{22}
}

func (x *ReactionCountByTypeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ReactionCountByTypeRequest) GetReactType() string {
	if x != nil {
		return x.ReactType
	}
	return ""
}

type ReactionCountByTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count string `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReactionCountByTypeResponse) Reset() {
	*x = ReactionCountByTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactionTypes_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReactionCountByTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionCountByTypeResponse) ProtoMessage() {}

func (x *ReactionCountByTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reactionTypes_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionCountByTypeResponse.ProtoReflect.Descriptor instead.
func (*ReactionCountByTypeResponse) Descriptor() ([]byte, []int) {
	return file_reactionTypes_proto_rawDescGZIP(), []int{23}
}

func (x *ReactionCountByTypeResponse) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

var File_reactionTypes_proto protoreflect.FileDescriptor

var file_reactionTypes_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x37, 0x0a, 0x0d, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x63,
	0x74, 0x73, 0x22, 0x32, 0x0a, 0x18, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x73, 0x22, 0x54, 0x0a, 0x19, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x0d, 0x72,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x54, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52,
	0x0d, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x19,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x53, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52,
	0x0d, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x69,
	0x0a, 0x09, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x14, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x44, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x46, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x31, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x47, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x37, 0x0a, 0x1d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x50, 0x6f, 0x73,
	0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74,
	0x49, 0x64, 0x22, 0x30, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x6f, 0x6b, 0x22, 0x53, 0x0a, 0x21, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x22, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x22,
	0x66, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x61,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x33, 0x0a, 0x19, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x1a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x52, 0x0a, 0x1a, 0x52, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x33, 0x0a, 0x1b,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x32, 0xc2, 0x07, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x12, 0x1c,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46,
	0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x18, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12,
	0x21, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x12, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x13,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_reactionTypes_proto_rawDescOnce sync.Once
	file_reactionTypes_proto_rawDescData = file_reactionTypes_proto_rawDesc
)

func file_reactionTypes_proto_rawDescGZIP() []byte {
	file_reactionTypes_proto_rawDescOnce.Do(func() {
		file_reactionTypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_reactionTypes_proto_rawDescData)
	})
	return file_reactionTypes_proto_rawDescData
}

var file_reactionTypes_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_reactionTypes_proto_goTypes = []interface{}{
	(*ReactionTypes)(nil),                      // 0: pb.ReactionTypes
	(*PostReactionTypesRequest)(nil),           // 1: pb.PostReactionTypesRequest
	(*PostReactionTypesResponse)(nil),          // 2: pb.PostReactionTypesResponse
	(*GetReactionTypeIDRequest)(nil),           // 3: pb.GetReactionTypeIDRequest
	(*GetReactionTypeIDResponse)(nil),          // 4: pb.GetReactionTypeIDResponse
	(*GetReactionTypesRequest)(nil),            // 5: pb.GetReactionTypesRequest
	(*GetReactionTypesResponse)(nil),           // 6: pb.GetReactionTypesResponse
	(*Reactions)(nil),                          // 7: pb.Reactions
	(*PostReactionsRequest)(nil),               // 8: pb.PostReactionsRequest
	(*PostReactionsResponse)(nil),              // 9: pb.PostReactionsResponse
	(*GetUserByPostIDRequest)(nil),             // 10: pb.GetUserByPostIDRequest
	(*GetUserByPostIDResponse)(nil),            // 11: pb.GetUserByPostIDResponse
	(*GetReactByUserIDRequest)(nil),            // 12: pb.GetReactByUserIDRequest
	(*GetReactByUserIDResponse)(nil),           // 13: pb.GetReactByUserIDResponse
	(*DeleteReactionByPostIDRequest)(nil),      // 14: pb.DeleteReactionByPostIDRequest
	(*DeleteReactionByPostIDResponse)(nil),     // 15: pb.DeleteReactionByPostIDResponse
	(*DeleteReactionByUserPostIDRequest)(nil),  // 16: pb.DeleteReactionByUserPostIDRequest
	(*DeleteReactionByUserPostIDResponse)(nil), // 17: pb.DeleteReactionByUserPostIDResponse
	(*UpdateReactionsRequest)(nil),             // 18: pb.UpdateReactionsRequest
	(*UpdateReactionsResponse)(nil),            // 19: pb.UpdateReactionsResponse
	(*TotalReactionCountRequest)(nil),          // 20: pb.TotalReactionCountRequest
	(*TotalReactionCountResponse)(nil),         // 21: pb.TotalReactionCountResponse
	(*ReactionCountByTypeRequest)(nil),         // 22: pb.ReactionCountByTypeRequest
	(*ReactionCountByTypeResponse)(nil),        // 23: pb.ReactionCountByTypeResponse
}
var file_reactionTypes_proto_depIdxs = []int32{
	0,  // 0: pb.PostReactionTypesResponse.reactionTypes:type_name -> pb.ReactionTypes
	0,  // 1: pb.GetReactionTypeIDResponse.reactionTypes:type_name -> pb.ReactionTypes
	0,  // 2: pb.GetReactionTypesResponse.reactionTypes:type_name -> pb.ReactionTypes
	7,  // 3: pb.PostReactionsResponse.reactions:type_name -> pb.Reactions
	7,  // 4: pb.GetUserByPostIDResponse.reactions:type_name -> pb.Reactions
	7,  // 5: pb.GetReactByUserIDResponse.reactions:type_name -> pb.Reactions
	7,  // 6: pb.UpdateReactionsResponse.reactions:type_name -> pb.Reactions
	1,  // 7: pb.ReactionService.PostReactionTypes:input_type -> pb.PostReactionTypesRequest
	3,  // 8: pb.ReactionService.GetReactionTypeID:input_type -> pb.GetReactionTypeIDRequest
	5,  // 9: pb.ReactionService.GetReactionTypes:input_type -> pb.GetReactionTypesRequest
	8,  // 10: pb.ReactionService.PostReactions:input_type -> pb.PostReactionsRequest
	10, // 11: pb.ReactionService.GetUserByPostID:input_type -> pb.GetUserByPostIDRequest
	12, // 12: pb.ReactionService.GetReactByUserID:input_type -> pb.GetReactByUserIDRequest
	14, // 13: pb.ReactionService.DeleteReactionByPostID:input_type -> pb.DeleteReactionByPostIDRequest
	16, // 14: pb.ReactionService.DeleteReactionByUserPostID:input_type -> pb.DeleteReactionByUserPostIDRequest
	18, // 15: pb.ReactionService.UpdateReactions:input_type -> pb.UpdateReactionsRequest
	20, // 16: pb.ReactionService.TotalReactionCount:input_type -> pb.TotalReactionCountRequest
	22, // 17: pb.ReactionService.ReactionCountByType:input_type -> pb.ReactionCountByTypeRequest
	2,  // 18: pb.ReactionService.PostReactionTypes:output_type -> pb.PostReactionTypesResponse
	4,  // 19: pb.ReactionService.GetReactionTypeID:output_type -> pb.GetReactionTypeIDResponse
	6,  // 20: pb.ReactionService.GetReactionTypes:output_type -> pb.GetReactionTypesResponse
	9,  // 21: pb.ReactionService.PostReactions:output_type -> pb.PostReactionsResponse
	11, // 22: pb.ReactionService.GetUserByPostID:output_type -> pb.GetUserByPostIDResponse
	13, // 23: pb.ReactionService.GetReactByUserID:output_type -> pb.GetReactByUserIDResponse
	15, // 24: pb.ReactionService.DeleteReactionByPostID:output_type -> pb.DeleteReactionByPostIDResponse
	17, // 25: pb.ReactionService.DeleteReactionByUserPostID:output_type -> pb.DeleteReactionByUserPostIDResponse
	19, // 26: pb.ReactionService.UpdateReactions:output_type -> pb.UpdateReactionsResponse
	21, // 27: pb.ReactionService.TotalReactionCount:output_type -> pb.TotalReactionCountResponse
	23, // 28: pb.ReactionService.ReactionCountByType:output_type -> pb.ReactionCountByTypeResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_reactionTypes_proto_init() }
func file_reactionTypes_proto_init() {
	if File_reactionTypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reactionTypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReactionTypes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostReactionTypesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostReactionTypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactionTypeIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactionTypeIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactionTypesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactionTypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostReactionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostReactionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByPostIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByPostIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReactByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReactionByPostIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReactionByPostIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReactionByUserPostIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReactionByUserPostIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReactionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReactionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalReactionCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalReactionCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReactionCountByTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactionTypes_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReactionCountByTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reactionTypes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reactionTypes_proto_goTypes,
		DependencyIndexes: file_reactionTypes_proto_depIdxs,
		MessageInfos:      file_reactionTypes_proto_msgTypes,
	}.Build()
	File_reactionTypes_proto = out.File
	file_reactionTypes_proto_rawDesc = nil
	file_reactionTypes_proto_goTypes = nil
	file_reactionTypes_proto_depIdxs = nil
}
